version: 0.0

os: linux

files:
  - source: spring-petclinic-3.2.0-SNAPSHOT.jar
    destination: /tmp

hooks:
  ApplicationStart:
    - location: start-process.sh
      timeout: 300
      runas: root
