version: 0.0

os: linux

files:
  - source: spring-petclinic-3.2.0-SNAPSHOT.jar
    destination: /tmp

hooks:
  #ApplicationStop is special because it runs before new  archive bundle is downloaded
  ApplicationStop:
      - location: stop-process.sh
        timeout: 300
        runas: root
  ApplicationStart:
    - location: start-process.sh
      timeout: 300
      runas: root

