version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      #- ./mvnw clean install
      #- ./mvnw install -DskipTests
      - ./mvnw clean test -Dtest=org.springframework.samples.petclinic.model.*Tests
      - ./mvnw test       -Dtest=org.springframework.samples.petclinic.owner.*Tests
      - ./mvnw package

  post_build:
    commands:
      - echo Build completed on `date`

reports:
  integration-tests:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    discard-paths: yes
    file-format: JUNITXML
artifacts:
  files:
    - target/spring-petclinic-3.2.0-SNAPSHOT.jar
    - appspec.yml
    - start-process.sh
    - stop-process.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
