version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install -DskipTests
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  integration-tests:
    files:
      - '**/*'
    base-directory: 'target/surefire-reports'
    discard-paths: yes
    file-format: JUNITXML
artifacts:
  files:
    - target/spring-petclinic-3.2.0-SNAPSHOT.jar
    - appspec.yml
    - start-process.sh
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'
